services:
  db:
    image: postgres:15
    container_name: book_db
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bookuser" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - book-net

  fastapi:
    build: ./fastapi_app
    container_name: book_fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bookuser:bookpass@db:5432/bookdb
    volumes:
      - ./fastapi_app:/app
      - model_cache:/root/.cache/huggingface
    depends_on:
      db:
        condition: service_healthy
    networks:
      - book-net
    restart: "no" # Не перезапускать автоматически

  flask:
    build: ./flask_app
    container_name: book_flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://bookuser:bookpass@db:5432/bookdb
      - SECRET_KEY=dev-secret-key-change-in-production
      - ML_SERVICE_URL=http://fastapi:8000
    volumes:
      - ./flask_app:/app
    depends_on:
      - db
      - fastapi
    networks:
      - book-net
    restart: "no"

volumes:
  postgres_data:
  model_cache:

networks:
  book-net:
    driver: bridge
