version: '3.8'

services:
  model:
    build: ./model
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./model_cache:/root/.cache/huggingface # кэш модели
    environment:
      - DB_PATH=/app/data/books.db
    networks:
      - book-net

  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_URL=http://model:8002
    depends_on:
      - model
    networks:
      - book-net

networks:
  book-net:
    driver: bridge
